/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BikeDAO;
import controller.EBikeDAO;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author dominick valentine
 */
public class addEBikeTostore extends javax.swing.JFrame {
    // all the needed fields and buttons
private JTextField typeField;
    private JTextField gearsField;
    private JTextField costField;
   
    private JTextField tireSizeField;
    private JButton addButton;
      private JTextField batteryWatts;
        private JTextField batteryLife;
   
         private JButton menubutton;
    
    // exit 
    private JButton endButton;
    
    // bike 
    private EBikeDAO bDAO;
    /**
     * Creates new form addEBikeTostore
     */
    public addEBikeTostore() {
       
 //   private addBikeTostore bb;
    /**
     * Creates new form BikeStore
     */
   
         super("Bike GUI");
        setLayout(new BorderLayout());
         // Create the input fields and labels
        JPanel inputPanel = new JPanel(new GridLayout(6, 2));
        inputPanel.add(new JLabel("Bike type:"));
        inputPanel.add(typeField = new JTextField());
        inputPanel.add(new JLabel("Number of gears:"));
        inputPanel.add(gearsField = new JTextField());
        inputPanel.add(new JLabel("Cost:"));
        inputPanel.add(costField = new JTextField());
       
        inputPanel.add(new JLabel("Tire size:"));
        inputPanel.add(tireSizeField = new JTextField());
        //batteryWatts;
        //private JTextField batteryLife;
         inputPanel.add(new JLabel("Battery Watts:"));
        inputPanel.add(batteryWatts= new JTextField());
         inputPanel.add(new JLabel("Battery Life:"));
        inputPanel.add(batteryLife= new JTextField());
        

        add(inputPanel, BorderLayout.NORTH);

        // Create the add button
        addButton = new JButton("Add");
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //
                addBike();
              // bDAO.createBike();
                
            }
        });
        
        add(addButton, BorderLayout.SOUTH);
       
        
 // end 
  endButton= new JButton("Exit");
   //endButton.setBounds(3,5,20,20);
  endButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
               exit();
            }
       });
        add(endButton,BorderLayout.EAST);
        // back to start 
       menubutton = new JButton("Menu");
        menubutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Menu abt = new Menu();
              abt.setLocationRelativeTo(null);
           
              abt.show();
              
              dispose();// close current frame after other one opens
                
             
            }
        });
        
        add(menubutton,BorderLayout.WEST);
        
    
        
        
    

        // Set the window size and make it visible
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
    
    private void exit(){
  System.exit(0);
 
 }
    // making the EBike
    private void addBike() {
      // taking user input and putting to a bike
        String type = typeField.getText();
        int gears = Integer.parseInt(gearsField.getText());
        double cost = Double.parseDouble(costField.getText());
        double tireSize = Double.parseDouble(tireSizeField.getText());
        int batteryw = Integer.parseInt(batteryWatts.getText());
        double batteryl =Double.parseDouble(batteryLife.getText());
        bDAO = new EBikeDAO();
        bDAO.createBike(type,gears,cost,tireSize,batteryw,batteryl);
        
    
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
