/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BikeDAO;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dominick valentine
 */
public class Look extends javax.swing.JFrame {
 private JButton lookButton;
    //private JTextField findField;
      private BikeDAO bDAO;

       private JButton menubutton;
// exit 
    private JButton endButton;
    /**
    /**
     * Creates new form Look
     */
    public Look() {
          
        // look
lookButton = new JButton("Look");
lookButton.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               look();
            }
       });

 add(lookButton,BorderLayout.WEST);
 // end 
  endButton= new JButton("Exit");
   //endButton.setBounds(3,5,20,20);
  endButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
               exit();
            }
       });
        add(endButton,BorderLayout.EAST);
        
         menubutton = new JButton("Menu");
        menubutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Menu abt = new Menu();
              abt.setLocationRelativeTo(null);
           
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(menubutton,BorderLayout.SOUTH);
        
       
        // Set the window size and make it visible
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
    
     private void exit(){
  System.exit(0);
 
 }
     // just prints out the whole file to the gui 
     private void look(){
        bDAO = new BikeDAO();
        bDAO.Look();
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
