/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.BorderLayout; 
import java.awt.GridLayout;
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener; 
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author dominick valentine
 */
public class Menu extends javax.swing.JFrame {
   
     private JButton addBikebutton; /** * Creates new form menu */
 private JButton addEBikebutton;
 private JButton lookbutton;
 private JButton findbutton;
 private JButton deletebutton;
     
     
     
    public Menu() {
       // initComponents();
        setLayout(new BorderLayout());
         // Create the input fields and labels
     
        addBikebutton = new JButton("Add a bike to the store");
        //addBikebutton.setBounds(50, 100, 100, 50);
        addBikebutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              addBikeTostore abt = new addBikeTostore();
              abt.setLocationRelativeTo(null);
              abt.setTitle("Bike shop");
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(addBikebutton,BorderLayout.SOUTH);
        setVisible(true);
        
        addEBikebutton = new JButton("Add a Ebike to the store");
        addEBikebutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              addEBikeTostore abt = new addEBikeTostore();
              abt.setLocationRelativeTo(null);
              abt.setTitle("EBike shop");
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(addEBikebutton,BorderLayout.NORTH);
        //addEBikebutton.setLocation(5, 5);
        
        
       lookbutton = new JButton("Look at  the store");
        lookbutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Look abt = new Look();
              abt.setLocationRelativeTo(null);
              abt.setTitle("Look at the shop");
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(lookbutton,BorderLayout.EAST);
        //addEBikebutton.setLocation(5, 5); 
        
        findbutton = new JButton("Search the store");
      //  findbutton.setBounds(100, 20, 100, 50);
        findbutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Searchstore abt = new Searchstore();
              abt.setLocationRelativeTo(null);
              abt.setTitle("shop");
              abt.show();
              
              dispose();// close current frame after other one opens
                
            
            }
        });
        
        add(findbutton,BorderLayout.WEST);
        setVisible(true);
        
         deletebutton= new JButton("Delete from the store");
        deletebutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Delete abt = new Delete();
              abt.setLocationRelativeTo(null);
              abt.setTitle("Delete");
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(deletebutton,BorderLayout.CENTER);
        
        // Set the window size and make it visible
        setSize(600, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu mf = new Menu();
                mf.setTitle("Menu");
               mf.setLocationRelativeTo(null);
               mf.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
