/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import controller.Biketest;
import controller.BikeDAO;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author dominick valentine
 */
public class Searchstore extends javax.swing.JFrame {
 private JButton findButton;
    private JTextField findField;
     // exit 
    private JButton endButton;
    
     private JButton menubutton;
    /**
     * Creates new form Searchstore
     */
     private BikeDAO bDAO;
    public Searchstore() {
          // super("Sea GUI");
        setLayout(new BorderLayout());
         // Create the input fields and labels
        JPanel inputPanel = new JPanel(new GridLayout(1, 1));
       
        //
         inputPanel.add(new JLabel("Search:"));
         inputPanel.add(findField = new JTextField());

        add(inputPanel, BorderLayout.NORTH);

        // Create the add button
       
        // find
findButton = new JButton("Search, This is case sensitive");
findButton.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
               find();
            }
       });

 add(findButton,BorderLayout.PAGE_END);
 // end 
  endButton= new JButton("Exit");
   //endButton.setBounds(3,5,20,20);
  endButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
               exit();
            }
       });
        add(endButton,BorderLayout.EAST);
        
        
         menubutton = new JButton("Menu");
        menubutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Menu abt = new Menu();
              abt.setLocationRelativeTo(null);
           
              abt.show();
              
              dispose();// close current frame after other one opens
                
                //addBike();
            }
        });
        
        add(menubutton,BorderLayout.WEST);
        
        
       
        // Set the window size and make it visible
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
    
   
    
  
    // finding 
    private void find(){
    String word = findField.getText();
         bDAO = new BikeDAO();
      bDAO.find(word);
        
        
    }
    
    
 private void exit(){
  System.exit(0);
 
 }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
